apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "php" . }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  APP_ENV: {{ .Values.php.env | quote }}
  APP_DEBUG: {{ .Values.php.debug | quote }}
  TRUSTED_HOSTS: {{ .Values.php.trustedHosts | quote }}
  TRUSTED_PROXIES: {{ join "," .Values.php.trustedProxies | quote }}