apiVersion: v1
kind: Secret
metadata:
  name: {{ template "php" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET: {{ .Values.php.secret | b64enc | quote }}
  DATABASE_URL: {{ include "databaseDsn" . | b64enc | quote }}
  MESSENGER_TRANSPORT_DSN: {{ include "messengerTransportDsn" . | b64enc | quote }}