apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "supervisor" . }}
  labels:
{{ include "labels" . | indent 4 }}
    component: supervisor
spec:
  replicas: {{ .Values.php.supervisor.replicaCount }}
  selector:
    matchLabels:
{{ include "matchLabels" . | indent 6 }}
      component: supervisor
  template:
    metadata:
      labels:
{{ include "labels" . | indent 8 }}
        component: supervisor
      annotations:
{{- if .Values.php.supervisor.podAnnotations }}
{{ toYaml .Values.php.supervisor.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: supervisor
        image: {{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - docker-entrypoint
        args:
          - supervisor
        livenessProbe:
          exec:
            command:
              - docker-healthcheck
              - supervisor
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - docker-healthcheck
              - supervisor
          initialDelaySeconds: 10
          timeoutSeconds: 5
        envFrom:
          - configMapRef:
              name: {{ template "php" . }}
          - secretRef:
              name: {{ template "php" . }}
          - secretRef:
              name: {{ template "supervisor" . }}
{{- if .Values.php.supervisor.resources }}
        resources:
{{ toYaml .Values.php.supervisor.resources | indent 10 }}
{{- end }}
        ports:
        - containerPort: 9000
          name: supervisor
      {{- with .Values.php.supervisor.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.php.supervisor.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.php.supervisor.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}