apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fpm" . }}
  labels:
{{ include "labels" . | indent 4 }}
    component: fpm
spec:
  replicas: {{ .Values.php.fpm.replicaCount }}
  selector:
    matchLabels:
{{ include "matchLabels" . | indent 6 }}
      component: fpm
  template:
    metadata:
      labels:
{{ include "labels" . | indent 8 }}
        component: fpm
      annotations:
{{- if .Values.php.fpm.podAnnotations }}
{{ toYaml .Values.php.fpm.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: fpm
        image: {{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - docker-entrypoint
        args:
          - fpm
        livenessProbe:
          exec:
            command:
              - docker-healthcheck
              - fpm
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - docker-healthcheck
              - fpm
          initialDelaySeconds: 10
          timeoutSeconds: 5
        envFrom:
          - configMapRef:
              name: {{ template "php" . }}
          - secretRef:
              name: {{ template "php" . }}
{{- if .Values.php.fpm.resources }}
        resources:
{{ toYaml .Values.php.fpm.resources | indent 10 }}
{{- end }}
        ports:
        - containerPort: 9000
          name: fpm
    {{- with .Values.php.fpm.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.php.fpm.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.php.fpm.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}