apiVersion: v1
kind: Service
metadata:
  name: {{ template "fpm" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: fpm
      port: 9000
      targetPort: 9000
  selector:
{{ include "matchLabels" . | indent 4 }}
    component: fpm